INSERT INTO pg_catalog.pg_config (name, setting) VALUES ('BINDIR', 'E:/programs/Postgres/bin');
INSERT INTO pg_catalog.pg_config (name, setting) VALUES ('DOCDIR', 'E:/programs/Postgres/doc');
INSERT INTO pg_catalog.pg_config (name, setting) VALUES ('HTMLDIR', 'E:/programs/Postgres/doc');
INSERT INTO pg_catalog.pg_config (name, setting) VALUES ('INCLUDEDIR', 'E:/programs/Postgres/include');
INSERT INTO pg_catalog.pg_config (name, setting) VALUES ('PKGINCLUDEDIR', 'E:/programs/Postgres/include');
INSERT INTO pg_catalog.pg_config (name, setting) VALUES ('INCLUDEDIR-SERVER', 'E:/programs/Postgres/include/server');
INSERT INTO pg_catalog.pg_config (name, setting) VALUES ('LIBDIR', 'E:/programs/Postgres/lib');
INSERT INTO pg_catalog.pg_config (name, setting) VALUES ('PKGLIBDIR', 'E:/programs/Postgres/lib');
INSERT INTO pg_catalog.pg_config (name, setting) VALUES ('LOCALEDIR', 'E:/programs/Postgres/share/locale');
INSERT INTO pg_catalog.pg_config (name, setting) VALUES ('MANDIR', 'E:/programs/Postgres/man');
INSERT INTO pg_catalog.pg_config (name, setting) VALUES ('SHAREDIR', 'E:/programs/Postgres/share');
INSERT INTO pg_catalog.pg_config (name, setting) VALUES ('SYSCONFDIR', 'E:/programs/Postgres/etc');
INSERT INTO pg_catalog.pg_config (name, setting) VALUES ('PGXS', 'E:/programs/Postgres/lib/pgxs/src/makefiles/pgxs.mk');
INSERT INTO pg_catalog.pg_config (name, setting) VALUES ('CONFIGURE', '--enable-thread-safety --enable-nls --with-ldap --with-openssl --with-ossp-uuid --with-libxml --with-libxslt --with-icu --with-tcl --with-perl --with-python');
INSERT INTO pg_catalog.pg_config (name, setting) VALUES ('CC', 'не записано');
INSERT INTO pg_catalog.pg_config (name, setting) VALUES ('CPPFLAGS', 'не записано');
INSERT INTO pg_catalog.pg_config (name, setting) VALUES ('CFLAGS', 'не записано');
INSERT INTO pg_catalog.pg_config (name, setting) VALUES ('CFLAGS_SL', 'не записано');
INSERT INTO pg_catalog.pg_config (name, setting) VALUES ('LDFLAGS', 'не записано');
INSERT INTO pg_catalog.pg_config (name, setting) VALUES ('LDFLAGS_EX', 'не записано');
INSERT INTO pg_catalog.pg_config (name, setting) VALUES ('LDFLAGS_SL', 'не записано');
INSERT INTO pg_catalog.pg_config (name, setting) VALUES ('LIBS', 'не записано');
INSERT INTO pg_catalog.pg_config (name, setting) VALUES ('VERSION', 'PostgreSQL 11.5');