GET http://localhost/messages?pageId=16
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

###
POST http://localhost/messages
Content-Type: application/json

{
  "pageId" : "16",
  "text" : "Bye!"
}

###

POST http://localhost/login
Content-Type: application/json

{
  "email" : "empty-15@mail.ru",
  "password" : "123"
}

###
GET http://localhost/profile
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxNyIsIm5hbWUiOiJSdXNsYW4iLCJzdXJuYW1lIjoiUGFzaGluIiwiZW1haWwiOiJlbXB0eS0xNUBtYWlsLnJ1IiwiaGFzaFBhc3N3b3JkIjoiJDJhJDEwJEFzODVBSzNZSnV1SzkxN1hteFd3UHV0aFNsaU9YNW1YVjRaZUFDZGN0TUZXMG80VmFORm9lIiwicm9sZSI6IlVTRVIiLCJwaG90b1BhdGgiOiJodHRwOi8vbG9jYWxob3N0L2ZpbGVzLzQ0ZTEzYzI0LWIxNDEtNDA0Yi05N2I4LTI5ZDRmNGMzMTBhZi5qcGcifQ.9Qc6e8s_DqhObX6YdVt6eu8q6dIjgnob5Tt2eI4vAiM

###
GET http://localhost/profile/posts
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxNyIsIm5hbWUiOiJSdXNsYW4iLCJzdXJuYW1lIjoiUGFzaGluIiwiZW1haWwiOiJlbXB0eS0xNUBtYWlsLnJ1IiwiaGFzaFBhc3N3b3JkIjoiJDJhJDEwJEFzODVBSzNZSnV1SzkxN1hteFd3UHV0aFNsaU9YNW1YVjRaZUFDZGN0TUZXMG80VmFORm9lIiwicm9sZSI6IlVTRVIiLCJwaG90b1BhdGgiOiJodHRwOi8vbG9jYWxob3N0L2ZpbGVzLzQ0ZTEzYzI0LWIxNDEtNDA0Yi05N2I4LTI5ZDRmNGMzMTBhZi5qcGcifQ.9Qc6e8s_DqhObX6YdVt6eu8q6dIjgnob5Tt2eI4vAiM

###
GET http://localhost/news
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxNyIsIm5hbWUiOiJSdXNsYW4iLCJzdXJuYW1lIjoiUGFzaGluIiwiZW1haWwiOiJlbXB0eS0xNUBtYWlsLnJ1IiwiaGFzaFBhc3N3b3JkIjoiJDJhJDEwJEFzODVBSzNZSnV1SzkxN1hteFd3UHV0aFNsaU9YNW1YVjRaZUFDZGN0TUZXMG80VmFORm9lIiwicm9sZSI6IlVTRVIiLCJwaG90b1BhdGgiOiJodHRwOi8vbG9jYWxob3N0L2ZpbGVzLzQ0ZTEzYzI0LWIxNDEtNDA0Yi05N2I4LTI5ZDRmNGMzMTBhZi5qcGcifQ.9Qc6e8s_DqhObX6YdVt6eu8q6dIjgnob5Tt2eI4vAiM

###
GET http://localhost/subs
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxNyIsIm5hbWUiOiJSdXNsYW4iLCJzdXJuYW1lIjoiUGFzaGluIiwiZW1haWwiOiJlbXB0eS0xNUBtYWlsLnJ1IiwiaGFzaFBhc3N3b3JkIjoiJDJhJDEwJEFzODVBSzNZSnV1SzkxN1hteFd3UHV0aFNsaU9YNW1YVjRaZUFDZGN0TUZXMG80VmFORm9lIiwicm9sZSI6IlVTRVIiLCJwaG90b1BhdGgiOiJodHRwOi8vbG9jYWxob3N0L2ZpbGVzLzQ0ZTEzYzI0LWIxNDEtNDA0Yi05N2I4LTI5ZDRmNGMzMTBhZi5qcGcifQ.9Qc6e8s_DqhObX6YdVt6eu8q6dIjgnob5Tt2eI4vAiM

###