GET  http://localhost/files/init
Accept: */*
Cache-Control: no-cache
Content-Type: application/json
###

GET  http://localhost/files/convert
Accept: */*
Cache-Control: no-cache
Content-Type: application/json
###

GET  http://localhost/users/38/files/png/convert
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

###

GET  http://localhost/users/38/files/information
Accept: */*
Cache-Control: no-cache
Content-Type: application/json
###
