<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title>SignUp</title>

    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>

    <link href='http://fonts.googleapis.com/css?family=Roboto' rel='stylesheet' type='text/css'>

</head>
<body >
<div>
    <form action="/signUp" method="post">
        <p></p>
        <input type="text" id="email" name="email" placeholder="write email..">
        <p></p>
        <input type="password" id="password" name="password" placeholder="write password..">
        <input type="submit">
    </form>
</div>
</body>
</html>